'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
function verify(directory, filename, manifest, imports, exports) {
  const binary = fs.readFileSync(path.join(directory, filename));
  const pin = manifest.files[filename];
  if (!pin || binary.length !== pin.bytes || crypto.createHash('sha256').update(binary).digest('hex') !== pin.sha256) throw new Error('Audio asset integrity failure: ' + filename);
  const module = new WebAssembly.Module(binary);
  const actual = WebAssembly.Module.imports(module).map(i => i.module + '.' + i.name + ':' + i.kind).sort();
  if (JSON.stringify(actual) !== JSON.stringify(imports.slice().sort())) throw new Error('Review changed audio ABI imports: ' + filename);
  const names = new Set(WebAssembly.Module.exports(module).map(i => i.name));
  for (const name of exports) if (!names.has(name)) throw new Error(filename + ' is missing ' + name);
}
const dfDirectory = path.join(root, 'audio/vendor/deepfilter');
const df = JSON.parse(fs.readFileSync(path.join(dfDirectory, 'manifest.json'), 'utf8'));
if (df.upstream.commit !== '773cf0ca65da1f82bc63ee5d8fd15d9314190231' || df.model !== 'DeepFilterNet3_ll') throw new Error('Review the pinned DFN3 engine/model before updating.');
verify(dfDirectory, 'df_bg.wasm', df, ['freqx.random_fill:function'], ['memory','freqx_df_create','freqx_df_free','freqx_df_input_ptr','freqx_df_output_ptr','freqx_df_latency_samples','freqx_df_process']);
const rnDirectory = path.join(root, 'audio/vendor/rnnoise');
const rn = JSON.parse(fs.readFileSync(path.join(rnDirectory, 'manifest.json'), 'utf8'));
if (rn.package !== '@shiguredo/rnnoise-wasm' || rn.version !== '2025.1.5') throw new Error('Review the restored RNNoise ABI before updating.');
verify(rnDirectory, 'rnnoise.wasm', rn, ['env.__assert_fail:function','env.emscripten_resize_heap:function','wasi_snapshot_preview1.fd_write:function'], ['memory','rnnoise_get_frame_size','rnnoise_create','rnnoise_destroy','rnnoise_process_frame','malloc','free']);
console.log('Verified local DFN3 SIMD and original RNNoise engines. No runtime downloads or compiler.');
const aecDirectory = path.join(root, 'audio/vendor/aec3');
const aecManifest = JSON.parse(fs.readFileSync(path.join(aecDirectory, 'manifest.json'), 'utf8'));
if (aecManifest.upstream.commit !== 'e1d663e86f2ab03269b9ae873af38d0103c4df3d') throw new Error('Review the AEC3 ABI before updating the pinned engine.');
verify(aecDirectory, 'aec3.wasm', aecManifest, ['a.a:memory','a.b:function','a.c:function','a.d:function','a.e:function','a.f:function','a.g:function'], Array.from('hijklmnopqrstuvwxyzAB'));
console.log('Verified pinned optional WebRTC AEC3 engine.');
require('./prepare-loopback.cjs');
